android.nonTransitiveRClass=true
android.enableArtifactTransforms=true
android.r8.fullMode=true
kotlin.code.style=official
kotlin.incremental.compilation=true
kotlin.incremental.compilation.js=true
ksp.incremental.interop=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true